[2022-09-07 11:25:40,699] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2022-09-06T00:00:00+00:00 [queued]>
[2022-09-07 11:25:40,706] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2022-09-06T00:00:00+00:00 [queued]>
[2022-09-07 11:25:40,707] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-09-07 11:25:40,707] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2022-09-07 11:25:40,707] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-09-07 11:25:40,726] {taskinstance.py:1038} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-09-06T00:00:00+00:00
[2022-09-07 11:25:40,729] {standard_task_runner.py:51} INFO - Started process 31256 to run task
[2022-09-07 11:25:40,737] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'is_api_available', '2022-09-06T00:00:00+00:00', '--job-id', '5', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp_5z82312']
[2022-09-07 11:25:40,737] {standard_task_runner.py:76} INFO - Job 5: Subtask is_api_available
[2022-09-07 11:25:40,798] {logging_mixin.py:103} INFO - Running <TaskInstance: user_processing.is_api_available 2022-09-06T00:00:00+00:00 [running]> on host airflowvm
[2022-09-07 11:25:40,868] {taskinstance.py:1230} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-09-06T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-06T00:00:00+00:00
[2022-09-07 11:25:40,868] {http.py:102} INFO - Poking: api/
[2022-09-07 11:25:40,877] {base.py:65} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: XXXXXXXX, extra: None
[2022-09-07 11:25:40,881] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-09-07 11:25:41,722] {base.py:245} INFO - Success criteria met. Exiting.
[2022-09-07 11:25:41,744] {taskinstance.py:1135} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20220906T000000, start_date=20220907T112540, end_date=20220907T112541
[2022-09-07 11:25:41,845] {taskinstance.py:1195} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-09-07 11:25:41,880] {local_task_job.py:118} INFO - Task exited with return code 0
