[2022-09-12 01:18:49,173] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.processing_tasks.task_2 2022-09-11T00:00:00+00:00 [queued]>
[2022-09-12 01:18:49,208] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.processing_tasks.task_2 2022-09-11T00:00:00+00:00 [queued]>
[2022-09-12 01:18:49,210] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-09-12 01:18:49,210] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-09-12 01:18:49,210] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-09-12 01:18:49,245] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_2> on 2022-09-11T00:00:00+00:00
[2022-09-12 01:18:49,393] {standard_task_runner.py:52} INFO - Started process 251661 to run task
[2022-09-12 01:18:49,403] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag.processing_tasks', 'task_2', '2022-09-11T00:00:00+00:00', '--job-id', '16', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpoitxvdm7', '--error-file', '/tmp/tmpu1yb07dq']
[2022-09-12 01:18:49,413] {standard_task_runner.py:77} INFO - Job 16: Subtask task_2
[2022-09-12 01:18:49,602] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.processing_tasks.task_2 2022-09-11T00:00:00+00:00 [running]> on host airflowvm
[2022-09-12 01:18:49,995] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag.processing_tasks
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2022-09-11T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-11T00:00:00+00:00
[2022-09-12 01:18:49,996] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2022-09-12 01:18:49,997] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2022-09-12 01:18:50,007] {subprocess.py:75} INFO - Output:
[2022-09-12 01:18:53,011] {subprocess.py:83} INFO - Command exited with return code 0
[2022-09-12 01:18:53,124] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag.processing_tasks, task_id=task_2, execution_date=20220911T000000, start_date=20220912T011849, end_date=20220912T011853
[2022-09-12 01:18:53,208] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-12 01:18:53,219] {local_task_job.py:151} INFO - Task exited with return code 0
